### ISSUE TITLE
Please remove my Vulkan-glTF-PBR application from performance comparisons

### ISSUE THREAD

**Issue by SaschaWillems** [stripe2933/vk-gltf-viewer#1]
My Vulkan-glTF-PBR application is not meant to be a fully fledged loader and is in no way optimized, esp. not for loading speeds. It's meant as a learning app for how to use glTF.

Can you please remove it from the comparison and also the included video?

**Comment by SaschaWillems** [comment]
Also this:

> For Vulkan-glTF-PBR, I don't know why but the swapchain is always presenting the image at fixed 120 FPS (regardless of the rendering time, even it took more than its vsync time!)

I don't really support Mac (I don't own such a device), so any perf. numbers gathered on that platform are probably useless or even wrong.

**Comment by stripe2933** [comment]
In accordance with your request, the following actions have been completed:  

- The application demonstration in the YouTube video has been blurred. Please note that this update may take some time to fully reflect.  
- Any mention of the application in the description of the YouTube video has been removed.  
- References to the application, as well as the associated benchmarking images, have been deleted from the GitHub repository.

I sincerely apologize for including the application in the comparison video without prior discussion.

Please feel free to reach out if you have any further concerns or questions.
