### ISSUE TITLE
Implicit assumptions in CMakeLists.txt find_package

### ISSUE THREAD

**Issue by dov** [stripe2933/vk-gltf-viewer#6]
Currently the `find_package()` lines in the top CMakeLists.txt express implicit assumptions about the installation of the dependent packages. Some of the dependencies are quite straightforward, as the packages are CMake based, e.g. glm, but others are not, e.g. imgui, and mikktspace, and then cmake will fail, as far as I understand.

I suggest making all the dependencies explicit by use of [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html), and either providing `Find<PackageName>.cmake` for projects without them, or just add their source code directly to the `vk-gltf-viewer` list of sources.

I might have a go at it on my own, in which case I'll add a pull request, but I'm not sure when I'll get around to it.

**Comment by stripe2933** [comment]
Are you by any chance not using vcpkg? This project is configured under the assumption that the user is using vcpkg.

**Comment by dov** [comment]
Oops! My mistake. I missed the use of vckpg instructions in the README.md file! I'm rebuilding with vcpkg. I'm closing this issue.
